langauge: generic
sudo: required
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
services:
    -docker

before_install:
    - docker build -t dumilonz/multicontainer-react-test -f ./client/Dockerfile.dev ./client
# here you can build other test suits in other folders

script:
    - docker run -e CI=true dumilonz/multicontainer-react-test npm test
    # here you can run different test suits

after_succes:
    # build production versions of all containers and push off to Dockerhub
    - docker build -t dumilonz/multicontainer-client ./client
    - docker build -t dumilonz/multicontainer-nginx ./nginx
    - docker build -t dumilonz/multicontainer-server ./server
    - docker build -t dumilonz/multicontainer-worker ./worker
    # login in docker CLI - put in encripted Travis CLI
    - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
    # take build containers and push to Dockerhub
    - docker push dumilonz/multicontainer-client
    - docker push dumilonz/multicontainer-nginx
    - docker push dumilonz/multicontainer-server
    - docker push dumilonz/multicontainer-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multicontainer-docker
    env: MulticontainerDocker-env
    bucket_name: elasticbeanstalk-us-east-2-622542045500
    bucket_path: multicontainer-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY